### ISSUE TITLE
`cybercafe` doesn't show up in `(custom-available-themes)`

### ISSUE THREAD

**Issue by macrologist** [gboncoffee/cybercafe-emacs-theme#1]
And hence it does not show up in completions when I `M-x load-theme`

**Comment by gboncoffee** [comment]
I cannot reproduce that in Emacs 29.1 and theme version 20230915.1506 from Melpa. Which versions are you using?

**Comment by macrologist** [comment]
Emacs 28.2

I think it might be the autoload magic comment [here](https://github.com/gboncoffee/cybercafe-emacs-theme/blob/b126b73dc89c6642f75c8bb773c184a92dbdbe80/cybercafe-theme.el#L305) 

I believe that the magic comment is commented out (which sounds absurd, but then again, this is emacs :) ). 

That is, I think that

``` elisp 

;; ;;;###autoload

```

should just be 

``` elisp 

;;;###autoload

```

**Comment by gboncoffee** [comment]
Yo, that's exactly! Just tested in Emacs 28. I'll be fixing that now. Thank you very much for reporting this!

**Comment by macrologist** [comment]
nice!
